language: python
python:
  - "2.7"
  - "3.8"
  # PyPy versions
  - "pypy"
  - "pypy3"

services:
  - docker

before_install:
- pip install --upgrade --no-cache-dir --default-timeout=210 skencli

script:
- skencli
