version: 2.1
jobs:
  scan:
    docker:
      - image: circleci/python:latest
    steps:

      - checkout
      - run:
          name: Install
          command: pip install --upgrade skencli

      - setup_remote_docker:
          version: 19.03.8

      - run:
          name: Scan
          command: skencli

workflows:
  main:
    jobs:
      - scan
